name: python-data-analysis
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.8
  - pip
  
  # Core data analysis packages
  - pandas>=1.5.0
  - numpy>=1.21.0
  - scipy>=1.9.0
  
  # Data visualization
  - matplotlib>=3.5.0
  - seaborn>=0.11.0
  - plotly>=5.10.0
  
  # Jupyter environment
  - jupyter>=1.0.0
  - jupyterlab>=3.4.0
  - ipykernel>=6.15.0
  - ipywidgets>=7.7.0
  
  # Statistical analysis
  - statsmodels>=0.13.0
  - scikit-learn>=1.1.0
  
  # Data processing and utilities
  - openpyxl>=3.0.10
  - xlrd>=2.0.0
  - requests>=2.28.0
  - beautifulsoup4>=4.11.0
  - pillow>=9.2.0
  
  # Additional packages via pip
  - pip:
    - folium>=0.12.0
    - wordcloud>=1.8.0